# [unstable.release]
# build-std = ["std", "panic_abort", "core", "alloc"]
# build-std-features = ["panic_immediate_abort"]

# [env]
# MANGANIS_SUPPORT = "true"

# [profile.dev]
# # rustflags = ["-Cdebuginfo=none", "-Cstrip=debuginfo"]
# # opt-level = "z"
# opt-level = "z"            # Optimization level.
# debug = false             # Include debug info.
# strip = "debuginfo"           # Removes symbols or debuginfo.
# # split-debuginfo = '...'  # Debug info splitting behavior.

[profile.dioxus-wasm]
inherits = "dev"
# opt-level = "z"
# debug = false
# strip = "debuginfo"

[profile.dioxus-server]
inherits = "dev"
opt-level = 2

[profile.dioxus-android]
inherits = "dev"
opt-level = 2
